# Hello, I have just made this UHCRun plugin for fun.
# I am going to improve some things in the future.
# I hope you will like it!
# If you have problems contact me: https://github.com/florixak

# This is main configuration file of UHCRun

settings:

  # Expanding plugins
  addons:
    use-Vault: true
    use-LuckPerms: false
    use-ProtocolLib: true
    use-PlaceholderAPI: true

  # Game
  game:
    auto-map-reset: true # name of game world is "world"
    allow-nether: false

    min-players: 2
    starting-message-at: 10 # start at <_> seconds

    teleport-after-mining: true

    # Countdowns
    countdowns:
      starting: 15 # seconds
      mining: 600 # seconds
      pvp: 600 # seconds
      deathmatch: 300 # seconds
      ending: 15 # seconds

    projectile-hit-hp: true
    no-explosions: false # global disable of explosions
    explode-block-destroy: true

    # Damage cause list:
    #   CONTACT, ENTITY_ATTACK, ENTITY_SWEEP_ATTACK, PROJECTILE, SUFFOCATION, FALL,
    #   FIRE, FIRE_TICK, MELTING, LAVA, DROWNING, BLOCK_EXPLOSION, ENTITY_EXPLOSION, VOID,
    #   LIGHTNING, SUICIDE, STARVATION, POISON, MAGIC, WITHER, FALLING_BLOCK, THORNS,
    #   DRAGON_BREATH, CUSTOM, FLY_INTO_WALL, HOT_FLOOR, CRAMMING, DRYOUT, FREEZE, SONIC_BOOM;
    disabled-in-mining:
      - FIRE
      - FIRE_TICK
      - LAVA
      - DROWNING
      - PROJECTILE
      - FALLING_BLOCK
      - ENTITY_EXPLOSION
      - BLOCK_EXPLOSION

    custom-drops: true
    random-drops: false # in development

  # Deathmatch
  deathmatch:
    enabled: true
    start-at: 3 # players, if -1 then automatic
    border-size: 40.0
    pvp-resistance-countdown: 10 # seconds, -1 = disable
    location: # center of deathmatch
      world: "world"
      x: 0.0
      y: 75.0
      z: 0.0

  # Border
  border:
    size: 450 # <..> x <..>
    damage: 1 # 2 = 1 HP, 4 = 2 HP ... 40 = 10HP
    warning-distance: 10 # blocks
    speed: 0.2 # blocks per second

  # Teams
  teams:
    team-mode: true
    max-size: 3
    friendly-fire: false

  # death chest
  death-chest:
    enabled: true
    expire: -1 # seconds, not expire if -1
    hologram-text: "&a%player%'s chest &7(%countdown%)"

  # Kits
  kits:
    enabled: true
    bought-forever: true
    open-on-starting-at: 10 # seconds, -1 = false, kits gui will open, like warning to choose kit

  # Kits
  perks:
    enabled: false # in progress
    full-time: false # true - not yet

  # Statistics
  statistics:
    # If false, player gets each kill to statistics immediately
    add-up-game-ends: false

    # Options: [ Wins, Kills, Deaths, Assists, Losses, Games-Played, UHC-Level ]
    # Need to be in []
    displayed-tops: [ "Wins", "Kills", "Deaths", "Assists", "Losses", "Games-Played", "UHC-Level" ]

    uhc-level:
      # Players will gain xp and increase their uhc run level
      enabled: true
      first-level: 0
      first-required-exp: 100.0
      exp-multiplier: 3.75

    player-stats:
      display-item: PLAYER_HEAD
      custom-name: "&a%player%"
      lore:
        - "&fLevel: &a%uhc-level%"
        - "&fRequired EXP: &a%required-uhc-exp%"
        - "&fMoney: &a%money%"
        - " "
        - "&fWins: &a%uhc-wins%"
        - "&fLosses: &a%uhc-losses%"
        - "&fKills: &a%uhc-kills%"
        - "&fDeaths: &a%uhc-deaths%"
    top-stats:
      display-item: PAPER
      custom-name: "&aTop Stats - %top-stats-mode%"
      lore:
        - "&f1. %uhc-top-1% - %uhc-top-1-value%"
        - "&f2. %uhc-top-2% - %uhc-top-2-value%"
        - "&f3. %uhc-top-3% - %uhc-top-3-value%"
        - "&f4. %uhc-top-4% - %uhc-top-4-value%"
        - "&f5. %uhc-top-5% - %uhc-top-5-value%"
        - " "
        - "&7(Click to change...)"

  # Rewards
  rewards:
    kill:
      money: 30
      exp: 60
      uhc-exp: 60
    assist:
      money: 10
      exp: 0
      uhc-exp: 20
    win:
      money: 150
      uhc-exp: 300
    lose:
      money: 50
      uhc-exp: 150
    activity:
      enabled: true
      money: 10
      uhc-exp: 20
      period: 300 # seconds
    level-up:
      base-reward: 10
      reward-coefficient: 1.2 # %base-reward% + (%reward-coefficient% ^ %uhc-level%)

  # End game commands - commands which is executed on game ends
  # IN PROGRESS...
  end-game-commands: [ ]

  # Tablist
  tablist:
    enabled: true # Works only with ProtocolLib!
    header: "&2&lUHC&a&lRun\n"
    solo-mode-player-list: "&7[%uhc-level%] &f%player%"
    team-mode-player-list: "&7[%uhc-level%] %team% &f%player%"
    footer: "\n&7www.github.com/florixak"

  # Auto broadcast
  auto-broadcast:
    enabled: false
    random-messages: true
    period: 10 # seconds

  # Custom nick
  custom-nick:
    enabled: true
    min-chars: 4 # < x

  # Selectors
  selectors:
    # Available menu - teams, kits, perks, custom-crafts, statistics
    teams:
      enabled: true
      display-name: "&aTeams"
      material: WHITE_WOOL
      slot: 0
    kits:
      enabled: true
      display-name: "&aKits"
      material: IRON_PICKAXE
      slot: 3
    perks:
      enabled: true
      display-name: "&aPerks"
      material: ARROW
      slot: 5
    custom-crafts:
      enabled: true
      display-name: "&aCustom Crafts"
      material: CRAFTING_TABLE
      slot: 4
    statistics:
      enabled: true
      display-name: "&aStatistics"
      material: PAPER # if null then player head
      slot: 8

  # MySQL database
  mysql:
    enabled: false
    host: "localhost"
    port: "3306"
    database: "uhcrun"
    username: "root"
    password: ""

  # Chat
  chat:
    # %player% - Name of player
    # %uhc-level% - UHC level of player
    # %luckperms-prefix% - If luckperms are allowed in config, displays player's prefix
    # %message% - Sent message
    # %level% - Player level

    lobby-format: "&7[%uhc-level%] %team% &f%player% &7» &f%message%"
    in-game-format: "&7[%uhc-level%] %team% &f%player% &7» &f%message%"
    dead-format: "&8[SPECTATOR] &7[%uhc-level%] %team% &7%player% » %message%"

    blocked-commands:
      - /pl
      - /plugins
      - /lp
      - /lp help
      - /lp editor
      - /luckperms
      - /luckperms editor
      - /luckperms help
      - /paper
      - /plugins
      - /paper
      - /plugins
      - /paper
      - /gm
      - /gmc
      - /gms
      - /gmsp
      - /gma
      - /gamemode
      - /gamemode 0
      - /gamemode 1
      - /gamemode 2
      - /gamemode 3
      - /gamemode c
      - /gamemode s
      - /gamemode a
      - /gamemode sp
      - /gamemode creative
      - /gamemode survival
      - /gamemode adventure
      - /gamemode spectator
      - /gm c
      - /gm s
      - /gm a
      - /gm sp
      - /gm spec
      - /give
      - /kill
      - /?