name: UHC-Revamp
version: '${project.version}'
main: me.florixak.uhcrevamp.UHCRevamp
api-version: 1.13
author: FloriXak
depend: [ PlaceholderAPI, Vault ]
softdepend: [ ProtocolLib, LuckPerms ]

commands:
  uhc:
    aliases: [ uhcr, uhcrevamp ]
    description: Only for admins to setup
  forcestart:
    aliases: [ start ]
    description: Force game start
  forceskip:
    aliases: [ skip ]
    description: Force game skip phase
  workbench:
    aliases: [ wb, craftingtable ]
    description: Opens remote workbench
  anvil:
    description: Opens remote anvil
  team:
    aliases: [ teams ]
    description: Opens teams gui
  kits:
    aliases: [ kit ]
    description: Opens kits gui
  perks:
    aliases: [ perk ]
    description: Opens perks gui
  recipes:
    aliases: [ crafts, recipe ]
    description: Opens recipes gui
  statistics:
    aliases: [ stats ]
    description: Opens players statistics
  revive:
    description: Revives dead player