name: UHC-Revamp
version: '${project.version}'
main: me.florixak.uhcrevamp.UHCRevamp
api-version: 1.13
author: FloriXak
softdepend: [ ProtocolLib, PlaceholderAPI, Vault, LuckPerms ]

commands:
  uhcrun:
    aliases: [ urun, uhcr ]
    description: Only for admins to setup
  forcestart:
    aliases: [ start ]
    description: Force game start
  workbench:
    aliases: [ wb, craftingtable ]
    description: Opens remote workbench
  anvil:
    description: Opens remote anvil
  team:
    aliases: [ teams ]
    description: Opens teams gui
  kits:
    aliases: [ kit ]
    description: Opens kits gui
  recipes:
    aliases: [ crafts, customrecipes ]
    description: Opens recipes gui
  statistics:
    aliases: [ stats ]
    description: Opens players statistics
  revive:
    description: Revives dead player